apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app-project
  labels:
    app: nest-app-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-app-project
  template:
    metadata:
      labels:
        app: nest-app-project
    spec:
      containers:
        - name: nest
          image: asia-southeast1-docker.pkg.dev/deploy-nest-app-project/nest-docker/api:c4a91b1f0ccedf2ee05f5dbe2f8e91ca1aa5a67c
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "3000"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nest-app-secret 
                  key: JWT_SECRET       

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nest-app-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: nest-app-secret
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nest-app-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nest-app-secret
                  key: DB_PASSWORD

            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nest-app-secret
                  key: DB_DATABASE
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nest-svc
spec:
  type: ClusterIP
  selector:
    app: nest-app-project
  ports:
    - name: http
      port: 8080
      targetPort: 3000
